### ISSUE TITLE
LICENSE please

### ISSUE THREAD

**Issue by IamManchanda** [StephenGrider/AlgoCasts#33]
Courses are paid but what about course material?
Shouldn't the material be open source so that students can fork freely?

**Comment by StephenGrider** [comment]
Hi Iam - I just added a license.  You are free to use examples in this repo as you please.  I do ask that you not create your own course based on these materials, but you can do pretty much anything else you wish.

**Comment by IamManchanda** [comment]
Thank you so so much stephen!
